---
- name: ensure proxy-config dir exists
  file:
    path: "{%raw%}{{nginx_proxy_config_home}}{%endraw%}"
    owner: nginx
    group: nginx
    mode: 0440
    state: directory

- name: template nginx config
  ansible.builtin.template:
    src: "{{cookiecutter.service_full_name}}.nginx.{{cookiecutter.nginx_proxy_type}}.conf.j2"
    dest: "{%raw%}{{nginx_proxy_config_home}}{%endraw%}/{{cookiecutter.service_full_name}}.{{cookiecutter.nginx_proxy_type}}.conf"
  notify: restart docker-nginx
  tags: [nginx]
